import type { Metadata } from "next";
import "@/app/ui/globals.css";
import Dashboardcontainer from "@/app/ui/dashboard/dashboardcontainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Dashboardcontainer>
          {children}
        </Dashboardcontainer>
      </body>
    </html>
  );
}
