import type { Metadata } from "next";
import "@/app/ui/globals.css";
import Dashboardcontainer from "@/app/ui/dashboard/dashboardcontainer";
import { Providers } from "./state_manager/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          <Dashboardcontainer>
            {children}
          </Dashboardcontainer>
        </Providers>
      </body>
    </html>
  );
}
