import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/ui/globals.css";
import DashboardContainer from "@/app/ui/dashboardcont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <DashboardContainer>{children}</DashboardContainer>
      </body>
    </html>
  );
}
