import "@/app/ui/globals.css";
import SideNav from "../ui/sideNav";
import DashTopNav from "../ui/dashTopNav";
import { Metadata } from "next";
import DashboardWrapper from "../ui/dashboard/wrapper";

export const DashboardMetaData: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
  };

export default function Layout({children}:{ children: React.ReactNode}) {
  return (
    <DashboardWrapper>{children}</DashboardWrapper>
  );
}